import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/page";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full h-screen lg:bg-[url('/images/header/headerBg.png')] lg:bg-no-repeat lg:bg-cover bg-center lg:min-h-[554px] flex flex-col px-4">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
